"""sqlalchemy sync

Revision ID: 1c15299b6495
Revises: 404de5d71f4f
Create Date: 2025-10-07 19:25:46.077754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c15299b6495'
down_revision: Union[str, None] = '404de5d71f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_palavras_exercicios',
    sa.Column('palavra_id', sa.Integer(), nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercicio_id'], ['tb_exercicios.id'], ),
    sa.ForeignKeyConstraint(['palavra_id'], ['tb_palavras.id'], ),
    sa.PrimaryKeyConstraint('palavra_id', 'exercicio_id')
    )
    op.add_column('tb_exercicios', sa.Column('prox_exercicio_id', sa.Integer(), nullable=True))
    op.alter_column('tb_exercicios', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_constraint('fk_prox_exercicio', 'tb_exercicios', type_='foreignkey')
    op.create_foreign_key(None, 'tb_exercicios', 'tb_exercicios', ['prox_exercicio_id'], ['id'])
    op.drop_column('tb_exercicios', 'prox_exercicio')
    op.add_column('tb_palavras', sa.Column('instrucoes', sa.String(), nullable=False))
    op.alter_column('tb_palavras', 'url_video',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('tb_perfis', 'atualizado_em')
    op.add_column('tb_progresso_usuarios', sa.Column('qtd_ex_completos', sa.Integer(), nullable=False))
    op.alter_column('tb_progresso_usuarios', 'status',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='I - Incompleto; C - Completo',
               existing_nullable=False,
               existing_server_default=sa.text("'I'::character varying"))
    op.drop_column('tb_progresso_usuarios', 'alterado_em')
    op.alter_column('tb_secoes', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('uk_nome_usuario', 'tb_usuarios', type_='unique')
    op.create_unique_constraint(None, 'tb_usuarios', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_usuarios', type_='unique')
    op.create_unique_constraint('uk_nome_usuario', 'tb_usuarios', ['nome_usuario'])
    op.alter_column('tb_secoes', 'descricao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('tb_progresso_usuarios', sa.Column('alterado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('tb_progresso_usuarios', 'status',
               existing_type=sa.VARCHAR(length=1),
               comment='I - Incompleto; C - Completo',
               existing_nullable=False,
               existing_server_default=sa.text("'I'::character varying"))
    op.drop_column('tb_progresso_usuarios', 'qtd_ex_completos')
    op.add_column('tb_perfis', sa.Column('atualizado_em', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.alter_column('tb_palavras', 'url_video',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('tb_palavras', 'instrucoes')
    op.add_column('tb_exercicios', sa.Column('prox_exercicio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tb_exercicios', type_='foreignkey')
    op.create_foreign_key('fk_prox_exercicio', 'tb_exercicios', 'tb_exercicios', ['prox_exercicio'], ['id'])
    op.alter_column('tb_exercicios', 'descricao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('tb_exercicios', 'prox_exercicio_id')
    op.drop_table('tb_palavras_exercicios')
    # ### end Alembic commands ###
