"""created conquista table

Revision ID: 1f0f39040a5e
Revises: 752402306ab2
Create Date: 2025-10-19 20:24:35.546095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0f39040a5e'
down_revision: Union[str, None] = '752402306ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_conquistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Enum('PRIMEIRO_SINAL', 'ALFABETO', 'NUMEROS', 'OUTROS', 'FRASES', 'ALIMENTOS', 'VERBOS', 'SAUDACOES', 'IDENTIDADE', name='nomeconquista'), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_conquista', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['tb_perfis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_conquistas')
    # ### end Alembic commands ###
