"""Schema Exercicios

Revision ID: 3cca2c3a1e4c
Revises: cc7c9034e524
Create Date: 2025-04-20 19:06:51.365845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cca2c3a1e4c'
down_revision: Union[str, None] = 'cc7c9034e524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palavras',
    sa.Column('id_palavra', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('url_video', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_palavra')
    )
    op.create_table('secoes',
    sa.Column('id_secao', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_secao')
    )
    op.create_table('exercicios',
    sa.Column('id_exercicio', sa.Integer(), nullable=False),
    sa.Column('id_secao', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('id_prox_tarefa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_secao'], ['secoes.id_secao'], ),
    sa.PrimaryKeyConstraint('id_exercicio')
    )
    op.create_table('exercicios_usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_exercicio', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'COMPLETO', name='exerciciostatus'), nullable=False),
    sa.ForeignKeyConstraint(['id_exercicio'], ['exercicios.id_exercicio'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_exercicio')
    )
    op.create_table('palavras_exercicios',
    sa.Column('id_palavra', sa.Integer(), nullable=False),
    sa.Column('id_exercicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_exercicio'], ['exercicios.id_exercicio'], ),
    sa.ForeignKeyConstraint(['id_palavra'], ['palavras.id_palavra'], ),
    sa.PrimaryKeyConstraint('id_palavra', 'id_exercicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('palavras_exercicios')
    op.drop_table('exercicios_usuarios')
    op.drop_table('exercicios')
    op.drop_table('secoes')
    op.drop_table('palavras')
    # ### end Alembic commands ###
