"""super usuarios

Revision ID: 3fa14f0b8e94
Revises: da82a3e5a119
Create Date: 2025-04-30 01:52:06.753704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa14f0b8e94'
down_revision: Union[str, None] = 'da82a3e5a119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('super_usuario', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'super_usuario')
    # ### end Alembic commands ###
