"""updated exercicio table

Revision ID: 752402306ab2
Revises: 1c15299b6495
Create Date: 2025-10-07 23:58:59.241833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752402306ab2'
down_revision: Union[str, None] = '1c15299b6495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_exercicios', sa.Column('eh_variacao', sa.Boolean(), nullable=False))
    op.add_column('tb_exercicios', sa.Column('nome_variacao', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_exercicios', 'nome_variacao')
    op.drop_column('tb_exercicios', 'eh_variacao')
    # ### end Alembic commands ###
