"""updated perfil table

Revision ID: cd900729c201
Revises: 1f0f39040a5e
Create Date: 2025-10-19 21:34:57.828625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd900729c201'
down_revision: Union[str, None] = '1f0f39040a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_perfis', sa.Column('nivel', sa.Integer(), nullable=False))
    op.add_column('tb_perfis', sa.Column('pontos_total', sa.Integer(), nullable=False))
    op.add_column('tb_perfis', sa.Column('pontos_nivel', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_perfis', 'pontos_nivel')
    op.drop_column('tb_perfis', 'pontos_total')
    op.drop_column('tb_perfis', 'nivel')
    # ### end Alembic commands ###
